# Generated by Django 4.0.2 on 2022-03-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='peso_ini',
            new_name='peso_inicial',
        ),
    ]
