# Generated by Django 4.0.2 on 2022-03-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_rename_peso_ini_vehiculo_peso_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='registro',
            new_name='vehiculo',
        ),
    ]
