# Generated by Django 4.0.2 on 2022-03-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0005_alter_registro_peso_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='peso_carga',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
