# Generated by Django 4.0.3 on 2022-04-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0008_configuracion_rename_dato_registro_registro_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='lectura',
            field=models.FloatField(default=0.0),
        ),
    ]
